In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns

In [11]:
df1 = pd.read_csv('datasets/Stunting.csv')
df2 = pd.read_csv('datasets/Wasting.csv')
df3 = pd.read_csv('datasets/Underweight_Overweight.csv')

In [12]:
df1.head()

,Number of household members,Wealth index factor score combined,Wealth index factor score for urban/rural,Mother's weight in kilograms,Mother's height in centimeters,Mother's BMI,v463f,Father's occupation,Birth weight in kilograms,Childs's age in months,...,Size of child at birth_Larger than Average,Size of child at birth_Smaller than Average,Size of child at birth_Very Large,Size of child at birth_Very Small,Size of child at birth_nan,Given child anything other than breast milk_No,Given child anything other than breast milk_Yes,Given child anything other than breast milk_nan,stunting_z_score,Stunting
0,6.0,-8.8131,-6.6716,43.8,140.6,2213.0,0.0,64.176851,2.400,12.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-80.500000,Severely Stunted
1,3.0,-13.1528,-11.4395,75.3,157.3,3041.0,0.0,64.176851,9.996,25.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-58.000000,Severely Stunted
2,5.0,12.6477,16.9070,80.1,161.7,3063.0,0.0,57.000000,2.500,57.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,218.500000,Normal
3,5.0,-0.9388,1.9798,60.0,139.4,3088.0,0.0,64.176851,3.000,11.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,168.000000,Normal
4,5.0,-0.5645,2.3910,42.0,146.1,1966.0,0.0,64.176851,2.600,29.742578,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,274.674119,Normal

In [13]:
df2.head()

,Number of household members,Wealth index factor score combined,Wealth index factor score for urban/rural,Mother's weight in kilograms,Mother's height in centimeters,Mother's BMI,v463f,Father's occupation,Birth weight in kilograms,Childs's age in months,...,Size of child at birth_Larger than Average,Size of child at birth_Smaller than Average,Size of child at birth_Very Large,Size of child at birth_Very Small,Size of child at birth_nan,Given child anything other than breast milk_No,Given child anything other than breast milk_Yes,Given child anything other than breast milk_nan,wasting_z_score,Wasting/Overweight
0,6.0,-8.8131,-6.6716,43.8,140.6,2213.0,0.0,64.176851,2.400,12.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.805000,Normal
1,3.0,-13.1528,-11.4395,75.3,157.3,3041.0,0.0,64.176851,9.996,25.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-0.580000,Normal
2,5.0,12.6477,16.9070,80.1,161.7,3063.0,0.0,57.000000,2.500,57.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.185000,Overweight
3,5.0,-0.9388,1.9798,60.0,139.4,3088.0,0.0,64.176851,3.000,11.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.680000,Normal
4,5.0,-0.5645,2.3910,42.0,146.1,1966.0,0.0,64.176851,2.600,29.742578,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.746741,Overweight

In [14]:
df3.head()

,Number of household members,Wealth index factor score combined,Wealth index factor score for urban/rural,Mother's weight in kilograms,Mother's height in centimeters,Mother's BMI,v463f,Father's occupation,Birth weight in kilograms,Childs's age in months,...,Size of child at birth_Larger than Average,Size of child at birth_Smaller than Average,Size of child at birth_Very Large,Size of child at birth_Very Small,Size of child at birth_nan,Given child anything other than breast milk_No,Given child anything other than breast milk_Yes,Given child anything other than breast milk_nan,underweight_z_score,Underweight/Overweight
0,6.0,-8.8131,-6.6716,43.8,140.6,2213.0,0.0,64.176851,2.400,12.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.610000,Normal
1,3.0,-13.1528,-11.4395,75.3,157.3,3041.0,0.0,64.176851,9.996,25.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.745000,Normal
2,5.0,12.6477,16.9070,80.1,161.7,3063.0,0.0,57.000000,2.500,57.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.675000,Normal
3,5.0,-0.9388,1.9798,60.0,139.4,3088.0,0.0,64.176851,3.000,11.000000,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.470000,Normal
4,5.0,-0.5645,2.3910,42.0,146.1,1966.0,0.0,64.176851,2.600,29.742578,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2.531932,Overweight

In [15]:
df1.columns

Index(['Number of household members', 'Wealth index factor score combined',
       'Wealth index factor score for urban/rural',
       'Mother's weight in kilograms', 'Mother's height in centimeters',
       'Mother's BMI', 'v463f', 'Father's occupation',
       'Birth weight in kilograms', 'Childs's age in months',
       'Childs's weight in kilograms', 'Childs's height in centimeters',
       'Child's Height/Age standard deviation',
       'Childs's BMI standard deviation (new WHO)', 'Dietary Index',
       'Type of place of residence_Rural', 'Type of place of residence_Urban',
       'Source of drinking water_92', 'Source of drinking water_96',
       'Source of drinking water_97', 'Source of drinking water_Bottled water',
       'Source of drinking water_Cart with small tank',
       'Source of drinking water_Piped into dwelling',
       'Source of drinking water_Piped to neighbor',
       'Source of drinking water_Piped to yard/plot',
       'Source of drinking water_Protected Spring',
       'Source of drinking water_Protected well',
       'Source of drinking water_Public tap/standpipe',
       'Source of drinking water_Rainwater',
       'Source of drinking water_River/lake/dam/ponds/stream/canal/irrigation channel',
       'Source of drinking water_Tanker truck',
       'Source of drinking water_Tubewell/ borehole',
       'Source of drinking water_Unprotected Spring',
       'Source of drinking water_Unprotected well',
       'Source of drinking water_nan',
       'Toilet facilities shared with other households_No',
       'Toilet facilities shared with other households_Not Dejure',
       'Toilet facilities shared with other households_Yes',
       'Toilet facilities shared with other households_nan',
       'Currently breastfeeding_No', 'Currently breastfeeding_Yes',
       'Currently breastfeeding_nan',
       'Mother's Under age 18 at time of birth_Age 18 or Older',
       'Mother's Under age 18 at time of birth_Under age 18',
       'Mother's Under age 18 at time of birth_nan',
       'Mother Smokes pipe full of tobacco_No',
       'Mother Smokes pipe full of tobacco_Yes',
       'Mother Smokes pipe full of tobacco_nan', 'Mother Chews tobacco_No',
       'Mother Chews tobacco_Yes', 'Mother Chews tobacco_nan',
       'Mother Snuffs by nose_No', 'Mother Snuffs by nose_Yes',
       'Mother Snuffs by nose_nan',
       'Frequency of mother smokes cigarettes_Does not smoke',
       'Frequency of mother smokes cigarettes_Everyday',
       'Frequency of mother smokes cigarettes_Someday',
       'Frequency of mother smokes cigarettes_nan',
       'Father's educational attainment_Complete Secondary',
       'Father's educational attainment_Higher',
       'Father's educational attainment_Incomplete Primary',
       'Father's educational attainment_Incomplete Secondary',
       'Father's educational attainment_No education',
       'Father's educational attainment_nan', 'Sex of child_Female',
       'Sex of child_Male', 'Sex of child_nan',
       'Size of child at birth_Average',
       'Size of child at birth_Larger than Average',
       'Size of child at birth_Smaller than Average',
       'Size of child at birth_Very Large',
       'Size of child at birth_Very Small', 'Size of child at birth_nan',
       'Given child anything other than breast milk_No',
       'Given child anything other than breast milk_Yes',
       'Given child anything other than breast milk_nan', 'stunting_z_score',
       'Stunting'],
      dtype='object')

In [16]:
df1.drop(['Wealth index factor score for urban/rural', "Mother's weight in kilograms", "Mother's height in centimeters",
         'v463f', "Father's occupation","Father's educational attainment_Complete Secondary",
       "Father's educational attainment_Higher",
       "Father's educational attainment_Incomplete Primary",
       "Father's educational attainment_Incomplete Secondary",
       "Father's educational attainment_No education",
       "Father's educational attainment_nan", "stunting_z_score",'Dietary Index'], axis=1)

,Number of household members,Wealth index factor score combined,Mother's BMI,Birth weight in kilograms,Childs's age in months,Childs's weight in kilograms,Childs's height in centimeters,Child's Height/Age standard deviation,Childs's BMI standard deviation (new WHO),Type of place of residence_Rural,...,Size of child at birth_Average,Size of child at birth_Larger than Average,Size of child at birth_Smaller than Average,Size of child at birth_Very Large,Size of child at birth_Very Small,Size of child at birth_nan,Given child anything other than breast milk_No,Given child anything other than breast milk_Yes,Given child anything other than breast milk_nan,Stunting
0,6.0,-8.81310,2213.0,2.400,12.000000,11.100000,90.000000,5.090000,-206.000000,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Severely Stunted
1,3.0,-13.15280,3041.0,9.996,25.000000,14.500000,102.700000,4.970000,-162.000000,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Severely Stunted
2,5.0,12.64770,3063.0,2.500,57.000000,26.200000,109.400000,0.140000,389.000000,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Normal
3,5.0,-0.93880,3088.0,3.000,11.000000,13.300000,76.600000,0.340000,354.000000,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Normal
4,5.0,-0.56450,1966.0,2.600,29.742578,48.588879,120.295435,5.223827,332.330484,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24398,10.0,17.24489,1787.0,3.000,54.000000,15.100000,102.600000,-0.620000,-69.000000,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Severely Stunted
24399,6.0,4.04940,1807.0,2.800,12.000000,8.200000,73.400000,-1.180000,-129.000000,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,Severely Stunted
24400,7.0,8.20700,2178.0,2.500,7.000000,7.800000,68.200000,-0.740000,-38.000000,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,Severely Stunted
24401,9.0,16.07320,2627.0,4.200,6.000000,7.200000,62.600000,-1.350000,84.000000,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Normal
24402,9.0,16.07320,2627.0,2.200,47.000000,12.100000,93.400000,-1.910000,-113.000000,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,Severely Stunted

In [17]:
df1.columns

Index(['Number of household members', 'Wealth index factor score combined',
       'Wealth index factor score for urban/rural',
       'Mother's weight in kilograms', 'Mother's height in centimeters',
       'Mother's BMI', 'v463f', 'Father's occupation',
       'Birth weight in kilograms', 'Childs's age in months',
       'Childs's weight in kilograms', 'Childs's height in centimeters',
       'Child's Height/Age standard deviation',
       'Childs's BMI standard deviation (new WHO)', 'Dietary Index',
       'Type of place of residence_Rural', 'Type of place of residence_Urban',
       'Source of drinking water_92', 'Source of drinking water_96',
       'Source of drinking water_97', 'Source of drinking water_Bottled water',
       'Source of drinking water_Cart with small tank',
       'Source of drinking water_Piped into dwelling',
       'Source of drinking water_Piped to neighbor',
       'Source of drinking water_Piped to yard/plot',
       'Source of drinking water_Protected Spring',
       'Source of drinking water_Protected well',
       'Source of drinking water_Public tap/standpipe',
       'Source of drinking water_Rainwater',
       'Source of drinking water_River/lake/dam/ponds/stream/canal/irrigation channel',
       'Source of drinking water_Tanker truck',
       'Source of drinking water_Tubewell/ borehole',
       'Source of drinking water_Unprotected Spring',
       'Source of drinking water_Unprotected well',
       'Source of drinking water_nan',
       'Toilet facilities shared with other households_No',
       'Toilet facilities shared with other households_Not Dejure',
       'Toilet facilities shared with other households_Yes',
       'Toilet facilities shared with other households_nan',
       'Currently breastfeeding_No', 'Currently breastfeeding_Yes',
       'Currently breastfeeding_nan',
       'Mother's Under age 18 at time of birth_Age 18 or Older',
       'Mother's Under age 18 at time of birth_Under age 18',
       'Mother's Under age 18 at time of birth_nan',
       'Mother Smokes pipe full of tobacco_No',
       'Mother Smokes pipe full of tobacco_Yes',
       'Mother Smokes pipe full of tobacco_nan', 'Mother Chews tobacco_No',
       'Mother Chews tobacco_Yes', 'Mother Chews tobacco_nan',
       'Mother Snuffs by nose_No', 'Mother Snuffs by nose_Yes',
       'Mother Snuffs by nose_nan',
       'Frequency of mother smokes cigarettes_Does not smoke',
       'Frequency of mother smokes cigarettes_Everyday',
       'Frequency of mother smokes cigarettes_Someday',
       'Frequency of mother smokes cigarettes_nan',
       'Father's educational attainment_Complete Secondary',
       'Father's educational attainment_Higher',
       'Father's educational attainment_Incomplete Primary',
       'Father's educational attainment_Incomplete Secondary',
       'Father's educational attainment_No education',
       'Father's educational attainment_nan', 'Sex of child_Female',
       'Sex of child_Male', 'Sex of child_nan',
       'Size of child at birth_Average',
       'Size of child at birth_Larger than Average',
       'Size of child at birth_Smaller than Average',
       'Size of child at birth_Very Large',
       'Size of child at birth_Very Small', 'Size of child at birth_nan',
       'Given child anything other than breast milk_No',
       'Given child anything other than breast milk_Yes',
       'Given child anything other than breast milk_nan', 'stunting_z_score',
       'Stunting'],
      dtype='object')

In [20]:
df_stunt = df1[['Wealth index factor score combined', "Mother's BMI", "Mother's Under age 18 at time of birth_Age 18 or Older",
       "Mother's Under age 18 at time of birth_Under age 18", "Mother's Under age 18 at time of birth_nan", "Sex of child_Female",
       'Sex of child_Male', 'Sex of child_nan', 'Size of child at birth_Average',
       'Size of child at birth_Larger than Average',
       'Size of child at birth_Smaller than Average',
       'Size of child at birth_Very Large',
       'Size of child at birth_Very Small', 'Size of child at birth_nan', 'Birth weight in kilograms', "Childs's age in months",
       "Childs's weight in kilograms", "Childs's height in centimeters", 'Type of place of residence_Rural', 'Type of place of residence_Urban', "Stunting"]]

In [21]:
df_stunt.head()

,Wealth index factor score combined,Mother's BMI,Mother's Under age 18 at time of birth_Age 18 or Older,Mother's Under age 18 at time of birth_Under age 18,Mother's Under age 18 at time of birth_nan,Sex of child_Female,Sex of child_Male,Sex of child_nan,Size of child at birth_Average,Size of child at birth_Larger than Average,...,Size of child at birth_Very Large,Size of child at birth_Very Small,Size of child at birth_nan,Birth weight in kilograms,Childs's age in months,Childs's weight in kilograms,Childs's height in centimeters,Type of place of residence_Rural,Type of place of residence_Urban,Stunting
0,-8.8131,2213.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2.400,12.000000,11.100000,90.000000,1.0,0.0,Severely Stunted
1,-13.1528,3041.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,9.996,25.000000,14.500000,102.700000,1.0,0.0,Severely Stunted
2,12.6477,3063.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2.500,57.000000,26.200000,109.400000,1.0,0.0,Normal
3,-0.9388,3088.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,3.000,11.000000,13.300000,76.600000,1.0,0.0,Normal
4,-0.5645,1966.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.600,29.742578,48.588879,120.295435,1.0,0.0,Normal

In [22]:
df_waste = df2[['Wealth index factor score combined', "Mother's BMI", "Mother's Under age 18 at time of birth_Age 18 or Older",
       "Mother's Under age 18 at time of birth_Under age 18", "Mother's Under age 18 at time of birth_nan", "Sex of child_Female",
       'Sex of child_Male', 'Sex of child_nan', 'Size of child at birth_Average',
       'Size of child at birth_Larger than Average',
       'Size of child at birth_Smaller than Average',
       'Size of child at birth_Very Large',
       'Size of child at birth_Very Small', 'Size of child at birth_nan', 'Birth weight in kilograms', "Childs's age in months",
       "Childs's weight in kilograms", "Childs's height in centimeters", 'Type of place of residence_Rural', 'Type of place of residence_Urban', "Wasting/Overweight"]]

In [23]:
df_waste.head()

,Wealth index factor score combined,Mother's BMI,Mother's Under age 18 at time of birth_Age 18 or Older,Mother's Under age 18 at time of birth_Under age 18,Mother's Under age 18 at time of birth_nan,Sex of child_Female,Sex of child_Male,Sex of child_nan,Size of child at birth_Average,Size of child at birth_Larger than Average,...,Size of child at birth_Very Large,Size of child at birth_Very Small,Size of child at birth_nan,Birth weight in kilograms,Childs's age in months,Childs's weight in kilograms,Childs's height in centimeters,Type of place of residence_Rural,Type of place of residence_Urban,Wasting/Overweight
0,-8.8131,2213.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2.400,12.000000,11.100000,90.000000,1.0,0.0,Normal
1,-13.1528,3041.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,9.996,25.000000,14.500000,102.700000,1.0,0.0,Normal
2,12.6477,3063.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2.500,57.000000,26.200000,109.400000,1.0,0.0,Overweight
3,-0.9388,3088.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,3.000,11.000000,13.300000,76.600000,1.0,0.0,Normal
4,-0.5645,1966.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.600,29.742578,48.588879,120.295435,1.0,0.0,Overweight

In [24]:
df_under_over = df3[['Wealth index factor score combined', "Mother's BMI", "Mother's Under age 18 at time of birth_Age 18 or Older",
       "Mother's Under age 18 at time of birth_Under age 18", "Mother's Under age 18 at time of birth_nan", "Sex of child_Female",
       'Sex of child_Male', 'Sex of child_nan', 'Size of child at birth_Average',
       'Size of child at birth_Larger than Average',
       'Size of child at birth_Smaller than Average',
       'Size of child at birth_Very Large',
       'Size of child at birth_Very Small', 'Size of child at birth_nan', 'Birth weight in kilograms', "Childs's age in months",
       "Childs's weight in kilograms", "Childs's height in centimeters", 'Type of place of residence_Rural', 'Type of place of residence_Urban', "Underweight/Overweight"]]

In [25]:
df_under_over.head()

,Wealth index factor score combined,Mother's BMI,Mother's Under age 18 at time of birth_Age 18 or Older,Mother's Under age 18 at time of birth_Under age 18,Mother's Under age 18 at time of birth_nan,Sex of child_Female,Sex of child_Male,Sex of child_nan,Size of child at birth_Average,Size of child at birth_Larger than Average,...,Size of child at birth_Very Large,Size of child at birth_Very Small,Size of child at birth_nan,Birth weight in kilograms,Childs's age in months,Childs's weight in kilograms,Childs's height in centimeters,Type of place of residence_Rural,Type of place of residence_Urban,Underweight/Overweight
0,-8.8131,2213.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2.400,12.000000,11.100000,90.000000,1.0,0.0,Normal
1,-13.1528,3041.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,9.996,25.000000,14.500000,102.700000,1.0,0.0,Normal
2,12.6477,3063.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,2.500,57.000000,26.200000,109.400000,1.0,0.0,Normal
3,-0.9388,3088.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,3.000,11.000000,13.300000,76.600000,1.0,0.0,Normal
4,-0.5645,1966.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,2.600,29.742578,48.588879,120.295435,1.0,0.0,Overweight

In [33]:
df_under_over.columns

Index(['Wealth index factor score combined', 'Mother's BMI',
       'Mother's Under age 18 at time of birth_Age 18 or Older',
       'Mother's Under age 18 at time of birth_Under age 18',
       'Mother's Under age 18 at time of birth_nan', 'Sex of child_Female',
       'Sex of child_Male', 'Sex of child_nan',
       'Size of child at birth_Average',
       'Size of child at birth_Larger than Average',
       'Size of child at birth_Smaller than Average',
       'Size of child at birth_Very Large',
       'Size of child at birth_Very Small', 'Size of child at birth_nan',
       'Birth weight in kilograms', 'Childs's age in months',
       'Childs's weight in kilograms', 'Childs's height in centimeters',
       'Type of place of residence_Rural', 'Type of place of residence_Urban',
       'Underweight/Overweight'],
      dtype='object')

In [34]:
df_under_over.iloc[0:1].values

array([[-8.8131, 2213.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 2.4, 12.0, 11.1, 90.0, 1.0, 0.0, 'Normal']],
      dtype=object)

In [30]:
df_stunt.to_csv('Stunting_11_2.csv', index=False)

In [32]:
df_waste.to_csv('Wasting_11_2.csv', index=False)

In [31]:
df_under_over.to_csv('Under_Over_11_2.csv', index=False)